steps:
  - name: 'hashicorp/terraform:1.6.5'
    args: ['init']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Force deleting leftover GKE cluster if it exists..."
        gcloud container clusters delete primary \
          --region us-central1 \
          --project cb-pipeline-demo \
          --quiet || echo "No leftover cluster found"

  - name: 'hashicorp/terraform:1.6.5'
    args: ['destroy', '-auto-approve', '-lock=false']

  - name: 'hashicorp/terraform:1.6.5'
    args: ['plan']

  - name: 'hashicorp/terraform:1.6.5'
    args: ['apply', '-auto-approve']

  # ✅ Snyk scan
  - name: 'snyk/snyk:docker'
    args: ['iac', 'test', '--severity-threshold=high']
    secretEnv: ['SNYK_TOKEN']

availableSecrets:
  secretManager:
    - versionName: projects/cb-pipeline-demo/secrets/SNYK_TOKEN/versions/latest
      env: 'SNYK_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY
