steps:
# Step 0: Terraform init
- name: 'hashicorp/terraform:1.6.5'
  args: ['init']

# Step 1: Terraform plan
- name: 'hashicorp/terraform:1.6.5'
  args: ['plan']

# Step 2: Terraform apply
- name: 'hashicorp/terraform:1.6.5'
  args: ['apply', '-auto-approve']

# Step 3: Extract kubeconfig from Terraform output
- name: 'hashicorp/terraform:1.6.5'
  entrypoint: 'sh'
  args:
    - -c
    - |
      terraform output -raw kubeconfig > /workspace/kubeconfig

# Step 4: Verify with kubectl (using generated kubeconfig)
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['get', 'nodes']
  env:
    - 'KUBECONFIG=/workspace/kubeconfig'

options:
  logging: CLOUD_LOGGING_ONLY
