steps:
# Step 1: Use the official Terraform image to run `init`
- name: 'hashicorp/terraform:1.6.5'
  args: ['init']
  env:
    - 'CLOUDSDK_CORE_PROJECT=[cb-pipeline-demo]'

# Step 2: Run `terraform plan`
- name: 'hashicorp/terraform:1.6.5'
  args: ['plan']
  env:
    - 'TF_VAR_gke_project_id=[cb-pipeline-demo]'
    - 'CLOUDSDK_CORE_PROJECT=[cb-pipeline-demo]'

# Step 3: Run `terraform apply` if the plan is successful
# The entrypoint is overridden to 'sh' to allow for multiple commands
- name: 'hashicorp/terraform:1.6.5'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      terraform apply -auto-approve
      # Use `gcloud` to get the kubeconfig for the GKE cluster
      gcloud container clusters get-credentials [primary] --region [us-central1] --project [cb-pipeline-demo
      # Verify access to the cluster with `kubectl`
      kubectl get nodes
  env:
    - 'TF_VAR_gke_project_id=[cb-pipeline-demo]'
    - 'CLOUDSDK_CORE_PROJECT=[cb-pipeline-demo]'

options:
  logging: CLOUD_LOGGING_ONLY