steps:
# Step 0: Terraform init
- name: 'hashicorp/terraform:1.6.5'
  args: ['init']
  env:
    - 'CLOUDSDK_CORE_PROJECT=cb-pipeline-demo'

# Step 1: Terraform plan
- name: 'hashicorp/terraform:1.6.5'
  args: ['plan']
  env:
    - 'CLOUDSDK_CORE_PROJECT=cb-pipeline-demo'

# Step 2: Terraform apply
- name: 'hashicorp/terraform:1.6.5'
  args: ['apply', '-auto-approve']
  env:
    - 'CLOUDSDK_CORE_PROJECT=cb-pipeline-demo'

options:
  logging: CLOUD_LOGGING_ONLY
