steps:
# Step 1: Use the official Terraform image to run `init`
- name: 'hashicorp/terraform:1.6.5'
  args: ['init']
  env:
    - 'CLOUDSDK_CORE_PROJECT=cb-pipeline-demo'

# Step 2: Run `terraform plan`
- name: 'hashicorp/terraform:1.6.5'
  args: ['plan']
  env:
    - 'TF_VAR_gke_project_id=cb-pipeline-demo'
    - 'CLOUDSDK_CORE_PROJECT=cb-pipeline-demo'

# Step 3a: Apply Terraform configuration
- name: 'hashicorp/terraform:1.6.5'
  args: ['apply', '-auto-approve']
  env:
    - 'TF_VAR_gke_project_id=cb-pipeline-demo'
    - 'CLOUDSDK_CORE_PROJECT=cb-pipeline-demo'

# Step 3b: Fetch kubeconfig using gcloud
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud container clusters get-credentials primary \
        --region us-central1 \
        --project cb-pipeline-demo

# Step 3c: Verify access to the cluster with kubectl
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['get', 'nodes']

options:
  logging: CLOUD_LOGGING_ONLY