steps:
  # Step 0: Terraform Init
  - name: 'hashicorp/terraform:1.6.5'
    args: ['init']

  # Step 1: Force delete leftover GKE cluster (ignore errors if not found)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Force deleting leftover GKE cluster if it exists..."
        gcloud container clusters delete primary --region=us-central1 --quiet || echo "No leftover cluster found"

  # Step 2: Terraform Destroy (cleanup before re-create)
  - name: 'hashicorp/terraform:1.6.5'
    args: ['destroy', '-auto-approve']

  # Step 3: Terraform Plan
  - name: 'hashicorp/terraform:1.6.5'
    args: ['plan']

  # Step 4: Terraform Apply
  - name: 'hashicorp/terraform:1.6.5'
    args: ['apply', '-auto-approve']

  # Step 5: Snyk Scan (auth via Secret Manager)
  - name: 'snyk/snyk:docker'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Authenticating with Snyk..."
        snyk auth "$$SNYK_TOKEN"
        echo "Running Snyk scan..."
        snyk test --docker your-docker-image:latest --file=Dockerfile

# Secret Manager injection
availableSecrets:
  secretManager:
    - versionName: projects/cb-pipeline-demo/secrets/snyk-token/versions/latest
      env: 'SNYK_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY
