apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: monitoring
type: Opaque
stringData:
  admin-user: ${GRAFANA_USER}
  admin-password: ${GRAFANA_PASSWORD}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: helm-prometheus-grafana
  namespace: monitoring
spec:
  template:
    spec:
      serviceAccountName: helm-job-sa
      restartPolicy: Never
      containers:
      - name: helm
        image: alpine/helm:3.12.0
        env:
        - name: GRAFANA_USER
          valueFrom:
            secretKeyRef:
              name: grafana-credentials
              key: admin-user
        - name: GRAFANA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-credentials
              key: admin-password
        command:
          - sh
          - -c
          - |
            echo "Adding Prometheus Helm repo..."
            helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
            helm repo update

            echo "Installing kube-prometheus-stack with custom Grafana creds..."
            helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
              --namespace monitoring --create-namespace \
              --set grafana.adminUser=$GRAFANA_USER \
              --set grafana.adminPassword=$GRAFANA_PASSWORD
