apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-admin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: helm-admin
    namespace: kube-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: helm-prometheus-grafana
  namespace: kube-system
spec:
  template:
    spec:
      serviceAccountName: helm-admin
      restartPolicy: Never
      containers:
        - name: helm
          image: alpine/helm:3.14.0
          command:
            - sh
            - -c
            - |
              helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
              helm repo update
              helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
                --namespace observability \
                --create-namespace \
                --set grafana.admin.existingSecret=grafana-credentials \
                --set grafana.admin.userKey=admin-user \
                --set grafana.admin.passwordKey=admin-password \
                --set prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.resources.requests.storage=50Gi \
                --set grafana.persistence.enabled=true
