apiVersion: batch/v1
kind: Job
metadata:
  name: helm-prometheus-grafana
  namespace: monitoring
spec:
  template:
    spec:
      serviceAccountName: helm-admin
      restartPolicy: Never
      containers:
      - name: helm
        image: alpine/helm:3.14.2
        command:
        - sh
        - -c
        - |
          # Add Prometheus community repo
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

          # Deploy Prometheus + Grafana with credentials from Kubernetes Secret
          helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack \
            --namespace monitoring \
            --create-namespace \
            --set grafana.admin.existingSecret=grafana-credentials \
            --set grafana.admin.userKey=admin-user \
            --set grafana.admin.passwordKey=admin-password
